#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${STEVEN_SERVER_ENV_FILE:-${BARRY_SERVER_ENV_FILE:-$ROOT_DIR/.env.server}}"
export STEVEN_JIAO_AI_LOOP_HOME="${STEVEN_JIAO_AI_LOOP_HOME:-$ROOT_DIR}"
export STEVEN_JIAO_AI_LOOP_AUTH_HOME="${STEVEN_JIAO_AI_LOOP_AUTH_HOME:-$HOME/.steven-jiao-ai-loop/auth}"
export PATH="$HOME/.nvm/versions/node/v22.22.1/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:${PATH:-}"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

cd "$ROOT_DIR"

STRATEGY_SYNC_SCRIPT="${STEVEN_LOOP_STRATEGY_SYNC_SCRIPT:-$ROOT_DIR/scripts/sync_steven_dashboard_strategy.py}"
STRATEGY_ENV_FILE="${STEVEN_LOOP_STRATEGY_ENV_FILE:-$ROOT_DIR/config/generated/dashboard-loop-strategy.env}"
if [[ "${STEVEN_LOOP_DASHBOARD_STRATEGY_ENABLED:-1}" != "0" && -f "$STRATEGY_SYNC_SCRIPT" ]]; then
  if python3 "$STRATEGY_SYNC_SCRIPT" \
    --api-base "${STEVEN_LOOP_DASHBOARD_API_BASE:-http://127.0.0.1:8770}" \
    --loop-root "$ROOT_DIR" \
    --owner "${STEVEN_LOOP_STRATEGY_OWNER:-焦千为}" \
    --uid "${STEVEN_LOOP_STRATEGY_UID:-2265845568}" \
    --output-dir "$(dirname "$STRATEGY_ENV_FILE")" \
    --min-accounts "${STEVEN_LOOP_STRATEGY_MIN_ACCOUNTS:-1}" \
    >>"$ROOT_DIR/runtime/logs/dashboard-strategy-sync.log" 2>&1; then
    :
  else
    printf '[%s] dashboard strategy sync failed; continuing with existing env\n' "$(date '+%F %T')" >>"$ROOT_DIR/runtime/logs/dashboard-strategy-sync.log"
  fi
fi
if [[ -f "$STRATEGY_ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$STRATEGY_ENV_FILE"
  set +a
fi

export BARRY_VIDEO_API_ENV="${STEVEN_VIDEO_API_ENV:-${BARRY_VIDEO_API_ENV:-test}}"
export BARRY_LOOP_PLATFORM="${STEVEN_LOOP_PLATFORM:-${BARRY_LOOP_PLATFORM:-FACEBOOK}}"
export BARRY_LOOP_COUNT="${STEVEN_LOOP_COUNT:-${BARRY_LOOP_COUNT:-20}}"
export BARRY_LOOP_MIN_SUCCESS_TARGET="${STEVEN_LOOP_MIN_SUCCESS_TARGET:-${BARRY_LOOP_MIN_SUCCESS_TARGET:-100}}"
export BARRY_LOOP_MAX_ROUNDS="${STEVEN_LOOP_MAX_ROUNDS:-${BARRY_LOOP_MAX_ROUNDS:-10}}"
export BARRY_LOOP_ROUND1_AT="${STEVEN_LOOP_ROUND1_AT:-${BARRY_LOOP_ROUND1_AT:-10:00}}"
export BARRY_LOOP_ROUND2_AT="${STEVEN_LOOP_ROUND2_AT:-${BARRY_LOOP_ROUND2_AT:-11:30}}"
export BARRY_LOOP_ROUND3_AT="${STEVEN_LOOP_ROUND3_AT:-${BARRY_LOOP_ROUND3_AT:-13:30}}"
export BARRY_LOOP_ROUND4_AT="${STEVEN_LOOP_ROUND4_AT:-${BARRY_LOOP_ROUND4_AT:-15:00}}"
export BARRY_LOOP_ROUND5_AT="${STEVEN_LOOP_ROUND5_AT:-${BARRY_LOOP_ROUND5_AT:-16:30}}"
export BARRY_LOOP_ROUND6_AT="${STEVEN_LOOP_ROUND6_AT:-${BARRY_LOOP_ROUND6_AT:-18:00}}"
export BARRY_LOOP_ROUND7_AT="${STEVEN_LOOP_ROUND7_AT:-${BARRY_LOOP_ROUND7_AT:-19:30}}"
export BARRY_LOOP_ROUND8_AT="${STEVEN_LOOP_ROUND8_AT:-${BARRY_LOOP_ROUND8_AT:-21:00}}"
export BARRY_LOOP_ROUND9_AT="${STEVEN_LOOP_ROUND9_AT:-${BARRY_LOOP_ROUND9_AT:-22:00}}"
export BARRY_LOOP_ROUND10_AT="${STEVEN_LOOP_ROUND10_AT:-${BARRY_LOOP_ROUND10_AT:-23:00}}"
export BARRY_LOOP_PUBLISH_SCHEDULE_ENABLED="${STEVEN_LOOP_PUBLISH_SCHEDULE_ENABLED:-${BARRY_LOOP_PUBLISH_SCHEDULE_ENABLED:-1}}"
export BARRY_LOOP_PUBLISH_WINDOW_START="${STEVEN_LOOP_PUBLISH_WINDOW_START:-${BARRY_LOOP_PUBLISH_WINDOW_START:-18:00}}"
export BARRY_LOOP_PUBLISH_WINDOW_END="${STEVEN_LOOP_PUBLISH_WINDOW_END:-${BARRY_LOOP_PUBLISH_WINDOW_END:-12:00}}"
export BARRY_LOOP_PUBLISH_TIMEZONE="${STEVEN_LOOP_PUBLISH_TIMEZONE:-${BARRY_LOOP_PUBLISH_TIMEZONE:-Asia/Shanghai}}"
export BARRY_LOOP_PUBLISH_LEAD_MINUTES="${STEVEN_LOOP_PUBLISH_LEAD_MINUTES:-${BARRY_LOOP_PUBLISH_LEAD_MINUTES:-5}}"
export BARRY_LOOP_TEAM_LANGUAGE_FILE="${STEVEN_LOOP_TEAM_LANGUAGE_FILE:-${BARRY_LOOP_TEAM_LANGUAGE_FILE:-$ROOT_DIR/config/fb-shortdrama-team-languages.json}}"
export BARRY_LOOP_CLIP_ENGINE="${STEVEN_LOOP_CLIP_ENGINE:-${BARRY_LOOP_CLIP_ENGINE:-ai_animation}}"
export BARRY_LOOP_CANDIDATE_SOURCE="${STEVEN_LOOP_CANDIDATE_SOURCE:-${BARRY_LOOP_CANDIDATE_SOURCE:-h5_new}}"
export BARRY_LOOP_ROUND1_KIND="${STEVEN_LOOP_ROUND1_KIND:-${BARRY_LOOP_ROUND1_KIND:-vidu_growth_startend}}"
export BARRY_LOOP_ROUND2_KIND="${STEVEN_LOOP_ROUND2_KIND:-${BARRY_LOOP_ROUND2_KIND:-vidu_growth_img2video}}"
export BARRY_LOOP_ROUND3_KIND="${STEVEN_LOOP_ROUND3_KIND:-${BARRY_LOOP_ROUND3_KIND:-batch_drama}}"
export BARRY_LOOP_ROUND4_KIND="${STEVEN_LOOP_ROUND4_KIND:-${BARRY_LOOP_ROUND4_KIND:-batch_drama}}"
export BARRY_LOOP_ROUND5_KIND="${STEVEN_LOOP_ROUND5_KIND:-${BARRY_LOOP_ROUND5_KIND:-batch_drama}}"
export BARRY_LOOP_ROUND6_KIND="${STEVEN_LOOP_ROUND6_KIND:-${BARRY_LOOP_ROUND6_KIND:-batch_drama}}"
export BARRY_LOOP_ROUND7_KIND="${STEVEN_LOOP_ROUND7_KIND:-${BARRY_LOOP_ROUND7_KIND:-batch_drama}}"
export BARRY_LOOP_ROUND8_KIND="${STEVEN_LOOP_ROUND8_KIND:-${BARRY_LOOP_ROUND8_KIND:-batch_drama}}"
export BARRY_LOOP_ROUND9_KIND="${STEVEN_LOOP_ROUND9_KIND:-${BARRY_LOOP_ROUND9_KIND:-batch_drama}}"
export BARRY_LOOP_ROUND10_KIND="${STEVEN_LOOP_ROUND10_KIND:-${BARRY_LOOP_ROUND10_KIND:-batch_drama}}"
export BARRY_LOOP_ALLOW_ACCOUNT_REUSE="${STEVEN_LOOP_ALLOW_ACCOUNT_REUSE:-${BARRY_LOOP_ALLOW_ACCOUNT_REUSE:-0}}"
export BARRY_LOOP_TEAM_IDS_FILE="${STEVEN_LOOP_TEAM_IDS_FILE:-${BARRY_LOOP_TEAM_IDS_FILE:-}}"
export BARRY_LOOP_TEAM_IDS="${STEVEN_LOOP_TEAM_IDS:-${BARRY_LOOP_TEAM_IDS:-}}"
export BARRY_LOOP_VIDU_GROWTH_SCRIPT="${STEVEN_LOOP_VIDU_GROWTH_SCRIPT:-${BARRY_LOOP_VIDU_GROWTH_SCRIPT:-$ROOT_DIR/../.codex/skills/beidou-novel-ops/scripts/vidu_growth_ab_round.js}}"
export BARRY_LOOP_VIDU_GROWTH_TEAM_IDS_FILE="${STEVEN_LOOP_VIDU_GROWTH_TEAM_IDS_FILE:-${BARRY_LOOP_VIDU_GROWTH_TEAM_IDS_FILE:-$HOME/.barry-video/account-splits/fb-novel-team-ids.txt}}"
export BARRY_LOOP_VIDU_GROWTH_VARIANTS="${STEVEN_LOOP_VIDU_GROWTH_VARIANTS:-${BARRY_LOOP_VIDU_GROWTH_VARIANTS:-4}}"
export BARRY_LOOP_VIDU_GROWTH_DURATION="${STEVEN_LOOP_VIDU_GROWTH_DURATION:-${BARRY_LOOP_VIDU_GROWTH_DURATION:-4}}"
export BARRY_LOOP_VIDU_GROWTH_RESOLUTION="${STEVEN_LOOP_VIDU_GROWTH_RESOLUTION:-${BARRY_LOOP_VIDU_GROWTH_RESOLUTION:-360p}}"
export BARRY_LOOP_VIDU_GROWTH_MODEL="${STEVEN_LOOP_VIDU_GROWTH_MODEL:-${BARRY_LOOP_VIDU_GROWTH_MODEL:-vidu2.0}}"
export BARRY_LOOP_STATE_ROOT="${STEVEN_LOOP_STATE_ROOT:-${BARRY_LOOP_STATE_ROOT:-$ROOT_DIR/runtime/daily-loop}}"
export BARRY_LOOP_REPORT_DIR="${STEVEN_LOOP_REPORT_DIR:-${BARRY_LOOP_REPORT_DIR:-$ROOT_DIR/runtime/reports/test-summary}}"
export BARRY_VIDEO_TEST_SUMMARY_DIR="${STEVEN_LOOP_TEST_SUMMARY_DIR:-${BARRY_VIDEO_TEST_SUMMARY_DIR:-$ROOT_DIR/runtime/reports/test-summary}}"
export BARRY_VIDEO_ANALYSIS_SUMMARY_DIR="${STEVEN_LOOP_ANALYSIS_SUMMARY_DIR:-${BARRY_VIDEO_ANALYSIS_SUMMARY_DIR:-$ROOT_DIR/runtime/reports/analysis}}"
export BARRY_VIDEO_AUTH_HOME="${BARRY_VIDEO_AUTH_HOME:-$STEVEN_JIAO_AI_LOOP_AUTH_HOME}"
export STEVEN_JIAO_AI_LOOP_LOCK_FILE="${STEVEN_JIAO_AI_LOOP_LOCK_FILE:-$ROOT_DIR/runtime/steven-jiao-ai-loop.lock}"
export BARRY_FEISHU_DAILY_LOOP_REPORT_PUSH="${STEVEN_FEISHU_DAILY_LOOP_REPORT_PUSH:-${BARRY_FEISHU_DAILY_LOOP_REPORT_PUSH:-0}}"
export BARRY_FEISHU_DAILY_LOOP_ROUND_REPORT_PUSH="${STEVEN_FEISHU_DAILY_LOOP_ROUND_REPORT_PUSH:-${BARRY_FEISHU_DAILY_LOOP_ROUND_REPORT_PUSH:-0}}"
export BARRY_FEISHU_ENV_FILE="${STEVEN_FEISHU_ENV_FILE:-${BARRY_FEISHU_ENV_FILE:-$HOME/.steven-jiao-ai-loop/feishu.env}}"
export BARRY_FEISHU_REPORT_LABEL="${STEVEN_FEISHU_REPORT_LABEL:-${BARRY_FEISHU_REPORT_LABEL:-Steven-jiao-ai-loop}}"

exec "$ROOT_DIR/scripts/run-daily-loop-scheduler.sh" "$@"
