#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${BARRY_SERVER_ENV_FILE:-$ROOT_DIR/.env.server}"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

cd "$ROOT_DIR"

export BARRY_VIDEO_API_ENV="${BARRY_VIDEO_API_ENV:-test}"
export BARRY_NOVEL_LOOP_PLATFORM="${BARRY_NOVEL_LOOP_PLATFORM:-FACEBOOK}"
export BARRY_NOVEL_LOOP_COUNT="${BARRY_NOVEL_LOOP_COUNT:-20}"
export BARRY_NOVEL_LOOP_ACCOUNT_POOL="${BARRY_NOVEL_LOOP_ACCOUNT_POOL:-facebook_novel_dedicated_10}"
export BARRY_NOVEL_LOOP_START_AT="${BARRY_NOVEL_LOOP_START_AT:-11:00}"
export BARRY_NOVEL_LOOP_END_AT="${BARRY_NOVEL_LOOP_END_AT:-09:00}"
export BARRY_NOVEL_LOOP_INTERVAL_SECONDS="${BARRY_NOVEL_LOOP_INTERVAL_SECONDS:-600}"
export BARRY_NOVEL_LOOP_STATE_ROOT="${BARRY_NOVEL_LOOP_STATE_ROOT:-$ROOT_DIR/runtime/novel-loop}"
export BARRY_NOVEL_LOOP_REPORT_DIR="${BARRY_NOVEL_LOOP_REPORT_DIR:-$ROOT_DIR/runtime/reports/novel-loop}"
export BARRY_VIDEO_TEST_SUMMARY_DIR="${BARRY_VIDEO_TEST_SUMMARY_DIR:-$ROOT_DIR/runtime/reports/novel-loop}"
export BARRY_NOVEL_DELETE_LOCAL_OUTPUT_AFTER_PUBLISH="${BARRY_NOVEL_DELETE_LOCAL_OUTPUT_AFTER_PUBLISH:-1}"
export BARRY_VIDEO_NOVEL_PUBLISH_FOLLOWUP_DELAY="${BARRY_VIDEO_NOVEL_PUBLISH_FOLLOWUP_DELAY:-1800}"
export BARRY_VIDEO_NOVEL_BATCH_CONCURRENCY="${BARRY_VIDEO_NOVEL_BATCH_CONCURRENCY:-3}"
export BARRY_VIDEO_NOVEL_VIDU_CONCURRENCY="${BARRY_VIDEO_NOVEL_VIDU_CONCURRENCY:-2}"

exec bash "$ROOT_DIR/scripts/run-novel-loop-scheduler.sh" "$@"
