#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${BARRY_SERVER_ENV_FILE:-$ROOT_DIR/.env.server}"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

cd "$ROOT_DIR"

export BARRY_VIDEO_API_ENV="${BARRY_VIDEO_API_ENV:-test}"
export BARRY_LOOP_PLATFORM="${BARRY_LOOP_PLATFORM:-FACEBOOK}"
export BARRY_LOOP_ACCOUNT_SUCCESS_TARGET="${BARRY_LOOP_ACCOUNT_SUCCESS_TARGET:-10}"
export BARRY_LOOP_ALLOW_ACCOUNT_REUSE="${BARRY_LOOP_ALLOW_ACCOUNT_REUSE:-1}"
export BARRY_LOOP_COUNT="${BARRY_LOOP_COUNT:-0}"
export BARRY_LOOP_STATE_ROOT="${BARRY_LOOP_STATE_ROOT:-$ROOT_DIR/runtime/continuous-loop}"
export BARRY_LOOP_REPORT_DIR="${BARRY_LOOP_REPORT_DIR:-$ROOT_DIR/runtime/reports/continuous-test-summary}"
export BARRY_FEISHU_DAILY_LOOP_REPORT_PUSH="${BARRY_FEISHU_DAILY_LOOP_REPORT_PUSH:-0}"
export BARRY_FEISHU_DAILY_LOOP_ROUND_NOTICE_PUSH="${BARRY_FEISHU_DAILY_LOOP_ROUND_NOTICE_PUSH:-0}"
export BARRY_LOOP_REALTIME_ENABLED="${BARRY_LOOP_REALTIME_ENABLED:-1}"
export BARRY_LOOP_REALTIME_ACCOUNT_POOL="${BARRY_LOOP_REALTIME_ACCOUNT_POOL:-facebook_drama_realtime_pool}"
export BARRY_LOOP_REALTIME_COUNT="${BARRY_LOOP_REALTIME_COUNT:-0}"
export BARRY_LOOP_REALTIME_RANK_ENABLED="${BARRY_LOOP_REALTIME_RANK_ENABLED:-1}"
export BARRY_LOOP_REALTIME_MATERIAL_ONLY="${BARRY_LOOP_REALTIME_MATERIAL_ONLY:-1}"
export BARRY_LOOP_ORDINARY_ACCOUNT_POOL="${BARRY_LOOP_ORDINARY_ACCOUNT_POOL:-facebook_drama_ordinary_pool}"
export BARRY_LOOP_ORDINARY_ENABLED="${BARRY_LOOP_ORDINARY_ENABLED:-1}"
export BARRY_LOOP_ORDINARY_COUNT="${BARRY_LOOP_ORDINARY_COUNT:-0}"
export BARRY_LOOP_FBHOT_TEST_ACCOUNT_POOL="${BARRY_LOOP_FBHOT_TEST_ACCOUNT_POOL:-facebook_drama_fbhot_test_pool}"
export BARRY_LOOP_FBHOT_TEST_ENABLED="${BARRY_LOOP_FBHOT_TEST_ENABLED:-1}"
export BARRY_LOOP_FBHOT_TEST_COUNT="${BARRY_LOOP_FBHOT_TEST_COUNT:-0}"
export BARRY_LOOP_FBHOT_TEST_FLYWHEEL_CONFIG="${BARRY_LOOP_FBHOT_TEST_FLYWHEEL_CONFIG:-conf/flywheel_fbhot_test.yaml}"
export BARRY_LOOP_CREATIVE_LIST_ENABLED="${BARRY_LOOP_CREATIVE_LIST_ENABLED:-0}"
export BARRY_LOOP_CREATIVE_LIST_ACCOUNT_POOL="${BARRY_LOOP_CREATIVE_LIST_ACCOUNT_POOL:-facebook_drama_creative_list_pool}"
export BARRY_LOOP_CREATIVE_LIST_COUNT="${BARRY_LOOP_CREATIVE_LIST_COUNT:-0}"
export BARRY_LOOP_CREATIVE_LIST_FLYWHEEL_CONFIG="${BARRY_LOOP_CREATIVE_LIST_FLYWHEEL_CONFIG:-conf/flywheel_creative_list.yaml}"
export BARRY_LOOP_CREATIVE_LIST_MATERIAL_ONLY="${BARRY_LOOP_CREATIVE_LIST_MATERIAL_ONLY:-1}"
export BARRY_LOOP_CREATIVE_LIST_DAY_ENABLED="${BARRY_LOOP_CREATIVE_LIST_DAY_ENABLED:-0}"
export BARRY_LOOP_CREATIVE_LIST_DAY_ACCOUNT_POOL="${BARRY_LOOP_CREATIVE_LIST_DAY_ACCOUNT_POOL:-facebook_drama_creative_list_day_pool}"
export BARRY_LOOP_CREATIVE_LIST_DAY_COUNT="${BARRY_LOOP_CREATIVE_LIST_DAY_COUNT:-0}"
export BARRY_LOOP_CREATIVE_LIST_DAY_FLYWHEEL_CONFIG="${BARRY_LOOP_CREATIVE_LIST_DAY_FLYWHEEL_CONFIG:-conf/flywheel_creative_list_day.yaml}"
export BARRY_LOOP_CREATIVE_LIST_DAY_MATERIAL_ONLY="${BARRY_LOOP_CREATIVE_LIST_DAY_MATERIAL_ONLY:-1}"
export BARRY_LOOP_REALTIME_DAY_ENABLED="${BARRY_LOOP_REALTIME_DAY_ENABLED:-0}"
export BARRY_LOOP_REALTIME_DAY_ACCOUNT_POOL="${BARRY_LOOP_REALTIME_DAY_ACCOUNT_POOL:-facebook_drama_realtime_day_pool}"
export BARRY_LOOP_REALTIME_DAY_COUNT="${BARRY_LOOP_REALTIME_DAY_COUNT:-0}"
export BARRY_LOOP_REALTIME_DAY_FLYWHEEL_CONFIG="${BARRY_LOOP_REALTIME_DAY_FLYWHEEL_CONFIG:-conf/flywheel_realtime_day.yaml}"
export BARRY_LOOP_REALTIME_DAY_MATERIAL_ONLY="${BARRY_LOOP_REALTIME_DAY_MATERIAL_ONLY:-1}"
export BARRY_LOOP_REALTIME_DAY_RANK_ENABLED="${BARRY_LOOP_REALTIME_DAY_RANK_ENABLED:-1}"
export BARRY_LOOP_REALTIME_SINGLE_ENABLED="${BARRY_LOOP_REALTIME_SINGLE_ENABLED:-0}"
export BARRY_LOOP_REALTIME_SINGLE_ACCOUNT_POOL="${BARRY_LOOP_REALTIME_SINGLE_ACCOUNT_POOL:-facebook_drama_realtime_single_pool}"
export BARRY_LOOP_REALTIME_SINGLE_COUNT="${BARRY_LOOP_REALTIME_SINGLE_COUNT:-0}"
export BARRY_LOOP_REALTIME_SINGLE_FLYWHEEL_CONFIG="${BARRY_LOOP_REALTIME_SINGLE_FLYWHEEL_CONFIG:-conf/flywheel_realtime_single.yaml}"
export BARRY_LOOP_REALTIME_SINGLE_MATERIAL_ONLY="${BARRY_LOOP_REALTIME_SINGLE_MATERIAL_ONLY:-1}"
export BARRY_LOOP_REALTIME_SINGLE_RANK_ENABLED="${BARRY_LOOP_REALTIME_SINGLE_RANK_ENABLED:-1}"
export BARRY_LOOP_REALTIME_SINGLE_WAIT_FOR_LINE="${BARRY_LOOP_REALTIME_SINGLE_WAIT_FOR_LINE:-realtime}"
export BARRY_LOOP_REALTIME_SINGLE_WAIT_FOR_LINE_POOL="${BARRY_LOOP_REALTIME_SINGLE_WAIT_FOR_LINE_POOL:-facebook_drama_realtime_pool}"
export BARRY_LOOP_YOURCHANNEL_ENABLED="${BARRY_LOOP_YOURCHANNEL_ENABLED:-0}"
export BARRY_LOOP_YOURCHANNEL_ACCOUNT_POOL="${BARRY_LOOP_YOURCHANNEL_ACCOUNT_POOL:-facebook_drama_yourchannel_pool}"
export BARRY_LOOP_YOURCHANNEL_COUNT="${BARRY_LOOP_YOURCHANNEL_COUNT:-0}"
export BARRY_LOOP_YOURCHANNEL_FLYWHEEL_CONFIG="${BARRY_LOOP_YOURCHANNEL_FLYWHEEL_CONFIG:-conf/flywheel_yourchannel.yaml}"
export BARRY_LOOP_RECENT_ORDER_ENABLED="${BARRY_LOOP_RECENT_ORDER_ENABLED:-0}"
export BARRY_LOOP_RECENT_ORDER_ACCOUNT_POOL="${BARRY_LOOP_RECENT_ORDER_ACCOUNT_POOL:-facebook_drama_recent_order_pool}"
export BARRY_LOOP_RECENT_ORDER_COUNT="${BARRY_LOOP_RECENT_ORDER_COUNT:-0}"
export BARRY_LOOP_RECENT_ORDER_FLYWHEEL_CONFIG="${BARRY_LOOP_RECENT_ORDER_FLYWHEEL_CONFIG:-conf/flywheel_recent_order.yaml}"
export BARRY_LOOP_STARDUSTTV_ENABLED="${BARRY_LOOP_STARDUSTTV_ENABLED:-1}"
export BARRY_LOOP_STARDUSTTV_ACCOUNT_POOL="${BARRY_LOOP_STARDUSTTV_ACCOUNT_POOL:-facebook_drama_stardusttv_pool}"
export BARRY_LOOP_STARDUSTTV_COUNT="${BARRY_LOOP_STARDUSTTV_COUNT:-0}"
export BARRY_LOOP_STARDUSTTV_FLYWHEEL_CONFIG="${BARRY_LOOP_STARDUSTTV_FLYWHEEL_CONFIG:-conf/flywheel_stardusttv.yaml}"
export BARRY_LOOP_REALTIME_FLYWHEEL_CONFIG="${BARRY_LOOP_REALTIME_FLYWHEEL_CONFIG:-}"
export BARRY_LOOP_ORDINARY_FLYWHEEL_CONFIG="${BARRY_LOOP_ORDINARY_FLYWHEEL_CONFIG:-}"
export BARRY_LOOP_DATE_ROLLOVER_RESET_ENABLED="${BARRY_LOOP_DATE_ROLLOVER_RESET_ENABLED:-1}"
export BARRY_LOOP_REALTIME_FB_HEAT_SIGNAL_FILE="${BARRY_LOOP_REALTIME_FB_HEAT_SIGNAL_FILE:-}"
export BARRY_LOOP_ORDINARY_FB_HEAT_SIGNAL_FILE="${BARRY_LOOP_ORDINARY_FB_HEAT_SIGNAL_FILE:-}"
export BARRY_LOOP_FBHOT_TEST_FB_HEAT_SIGNAL_FILE="${BARRY_LOOP_FBHOT_TEST_FB_HEAT_SIGNAL_FILE:-}"
export BARRY_LOOP_RESET_TARGETS_ON_START="${BARRY_LOOP_RESET_TARGETS_ON_START:-0}"

if [[ "$BARRY_LOOP_RESET_TARGETS_ON_START" == "1" ]]; then
  python3 - <<'PY'
from datetime import datetime
from pathlib import Path
import sys

ROOT_DIR = Path.cwd()
sys.path.insert(0, str(ROOT_DIR / "backend"))

from flywheel.daily_loop_targets import reset_success_target_window

state_root = Path((ROOT_DIR / "runtime" / "continuous-loop")).resolve()
day = datetime.now().strftime("%Y-%m-%d")

for line_name in ("realtime", "realtime_single", "realtime_day", "creative_list", "creative_list_day", "ordinary", "fbhot_test", "yourchannel", "recent_order", "stardusttv"):
    run_dir = state_root / day / line_name
    payload = reset_success_target_window(run_dir)
    print(
        f"[reset-on-start] {line_name}: generation={int(payload.get('generation') or 0)} "
        f"reset_at={str(payload.get('reset_at') or '').strip()}",
        flush=True,
    )
PY
fi

exec python3 "$ROOT_DIR/scripts/run-dual-line-supervisor.py" "$@"
